devgiants_ged_document_add:
    path:     /add
    defaults: { _controller: devGiantsGedDocumentBundle:Default:addDocuments }

devgiants_ged_document_search:
    path:     /search
    defaults: { _controller: devGiantsGedDocumentBundle:Default:searchDocuments }
