services:
#    dev_giants_ged_document.example:
#        class: devgiants\ged\DocumentBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    devgiants.ged.document.upload:
        class: devgiants\ged\DocumentBundle\Service\Upload
        arguments: ['@service_container']